### ISSUE TITLE
Crash ``'AsStringVisitor' object has no attribute 'visit_unknown'``

### ISSUE THREAD

**Issue by WolfgangFellger** [PyCQA/pylint#5048]
### Bug description

```python
pylint crashed with a ``AttributeError`` when parsing a file, see stacktrace below.

The example below is as condensed as possible (to the point of not making sense, I know):


def _find_prefix(a, b):
    common_prefix = []
    for i, j in zip(a, b):
        if i != j:
            break
        common_prefix.append(i)
    return tuple(common_prefix)


def _check_role_references(path, nearest_provider, provider_paths):
    checked_parent_providers = set()
    prefix = _find_prefix(path, nearest_provider)
    parent = prefix + (nearest_provider[len(prefix)],)
    if parent in checked_parent_providers:
        raise Exception()
```

### Command used

```shell
pylint faulty.py
```

### Pylint output

```shell
************* Module faulty
faulty.py:1:0: C0114: Missing module docstring (missing-module-docstring)
faulty.py:1:0: C0103: Argument name "a" doesn't conform to snake_case naming style (invalid-name)
faulty.py:1:0: C0103: Argument name "b" doesn't conform to snake_case naming style (invalid-name)
Exception on node <If l.14 at 0x7f419c74e9d0> in file '/opt/code/quidditch/faulty.py'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    callback(astroid)
  File "/usr/local/lib/python3.9/site-packages/pylint/checkers/base.py", line 1104, in visit_if
    self._check_using_constant_test(node, node.test)
  File "/usr/local/lib/python3.9/site-packages/pylint/checkers/base.py", line 1142, in _check_using_constant_test
    inferred = utils.safe_infer(test)
  File "/usr/local/lib/python3.9/site-packages/pylint/checkers/utils.py", line 1181, in safe_infer
    value = next(infer_gen)
  File "/usr/local/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 105, in infer
    yield from self._infer(context, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/astroid/inference.py", line 872, in _infer_compare
    retval = _do_compare(lhs, op, rhs)
  File "/usr/local/lib/python3.9/site-packages/astroid/inference.py", line 842, in _do_compare
    left, right = _to_literal(left), _to_literal(right)
  File "/usr/local/lib/python3.9/site-packages/astroid/inference.py", line 814, in _to_literal
    return ast.literal_eval(node.as_string())
  File "/usr/local/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 547, in as_string
    return AsStringVisitor()(self)
  File "/usr/local/lib/python3.9/site-packages/astroid/nodes/as_string.py", line 55, in __call__
    return node.accept(self).replace(DOC_NEWLINE, "\n")
  File "/usr/local/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 186, in accept
    return func(self)
  File "/usr/local/lib/python3.9/site-packages/astroid/nodes/as_string.py", line 516, in visit_tuple
    return "(%s, )" % node.elts[0].accept(self)
  File "/usr/local/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 185, in accept
    func = getattr(visitor, "visit_" + self.__class__.__name__.lower())
AttributeError: 'AsStringVisitor' object has no attribute 'visit_unknown'
faulty.py:1:0: F0001: Fatal error while checking 'faulty.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/uid1000/.cache/pylint/pylint-crash-2021-09-20-08.txt'. (fatal)
```

### Expected behavior

Not quite sure, but not crashing

### Pylint version

```shell
pylint 2.11.1
astroid 2.8.0
Python 3.9.7 (default, Sep  3 2021, 02:02:37) 
[GCC 10.2.1 20210110]
```

**Comment by DanielNoord** [comment]
I narrowed down the issue to:
```python
def func(parameter):
    variable = tuple(list()) + (parameter[len(tuple())],)
    if variable in set():
        raise Exception()
```

Going to see if I can find a solution, but someone might know what's up with this!

**Comment by cdce8p** [comment]
@DanielNoord The issue is caused by https://github.com/PyCQA/astroid/pull/979. `Unknown` doesn't have a `AsStringVisitor`, thus [astroid -> _to_literal](https://github.com/PyCQA/astroid/blob/5b516c9001fad3a8060c956821fb8f81f156c961/astroid/inference.py#L811-L814) will fail. It doesn't really make sense to add one either, since the node is `Unknown`. What should the return string be in that case?

Instead, I would recommend to add `AttributeError` to the list of exceptions [here](https://github.com/PyCQA/astroid/blob/5b516c9001fad3a8060c956821fb8f81f156c961/astroid/inference.py#L841-L845) and add a comment [here](https://github.com/PyCQA/astroid/blob/5b516c9001fad3a8060c956821fb8f81f156c961/astroid/inference.py#L812-L813) to explain that it can also raise `AttributeError`, since not all nodes do have a visitor.

**Comment by cdce8p** [comment]
@DanielNoord Would you like to prepare the PR? I can do the review if you link me.

**Comment by DanielNoord** [comment]
Yeah sure! Will probably do that tomorrow if that's okay?

**Comment by cdce8p** [comment]
> Yeah sure! Will probably do that tomorrow if that's okay?

No problem. Thanks!
