### ISSUE TITLE
AttributeError: 'ImportsChecker' object has no attribute '_module_pkg' after upgrading to 2.2.0 from 2.1.1

### ISSUE THREAD

**Issue by hodossy** [PyCQA/pylint#2613]
Here is the Traceback:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\astroid\decorators.py", line 31, in cached
    return cache[func]
KeyError: <bound method ImportsChecker._external_dependencies_info of <pylint.checkers.imports.ImportsChecker object at 0x0000017E0023FD30>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\lib\site-packages\pylint\__main__.py", line 8, in <module>
    pylint.run_pylint()
  File "C:\Program Files\Python36\lib\site-packages\pylint\__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "C:\Program Files\Python36\lib\site-packages\pylint\lint.py", line 1609, in __init__
    linter.generate_reports()
  File "C:\Program Files\Python36\lib\site-packages\pylint\lint.py", line 1182, in generate_reports
    sect = self.make_reports(self.stats, previous_stats)
  File "C:\Program Files\Python36\lib\site-packages\pylint\utils.py", line 1072, in make_reports
    r_cb(report_sect, stats, old_stats)
  File "C:\Program Files\Python36\lib\site-packages\pylint\checkers\imports.py", line 863, in _report_external_dependencies
    dep_info = _make_tree_defs(self._external_dependencies_info().items())
  File "C:\Program Files\Python36\lib\site-packages\wrapt\wrappers.py", line 562, in __call__
    args, kwargs)
  File "C:\Program Files\Python36\lib\site-packages\astroid\decorators.py", line 33, in cached
    cache[func] = result = func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\pylint\checkers\imports.py", line 904, in _external_dependencies_info
    return self._filter_dependencies_graph(internal=False)
  File "C:\Program Files\Python36\lib\site-packages\pylint\checkers\imports.py", line 893, in _filter_dependencies_graph
    package = self._module_pkg.get(importer, importer)
AttributeError: 'ImportsChecker' object has no attribute '_module_pkg'

### Steps to reproduce
1. use more than 1 job
2. have a project with nested modules (works fine for single files or modules)

### Current behavior
Throwing exception

### Expected behavior
Building the dependency graph as expected

### pylint --version output
__main__.py 2.2.0
astroid 2.0.2
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
