### ISSUE TITLE
Pylint 2.11.1 error - cannot import name 'ParamSpec' from 'typing_extensions'

### ISSUE THREAD

**Issue by vaibhavsdevalalikar** [PyCQA/pylint#5032]
### Bug description

```python
Pylint 2.11.1 throws error when working with pylint-json2html on python 3.7.12 on Azure devops pipeline with unbuntu 18.01 host
It was not happening before 17th Sep.
```

### Command used

```shell
python -m pylint --load-plugins=pylint_json2html --confidence=HIGH --output-format=jsonextended
```

### Pylint output

```shell
File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/astroid/__init__.py", line 54, in <module>
    from astroid import node_classes  # Deprecated, to remove later
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/astroid/node_classes.py", line 5, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/astroid/nodes/__init__.py", line 26, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/astroid/nodes/node_classes.py", line 45, in <module>
    from astroid import decorators, mixins, util
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/astroid/decorators.py", line 35, in <module>
    from typing_extensions import ParamSpec
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/typing_extensions.py)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/bin/pylint-json2html", line 5, in <module>
    from pylint_json2html import main
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pylint_json2html/__init__.py", line 18, in <module>
    from pylint.interfaces import IReporter
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pylint/interfaces.py", line 23, in <module>
    from astroid import nodes
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/astroid/__init__.py", line 54, in <module>
    from astroid import node_classes  # Deprecated, to remove later
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/astroid/node_classes.py", line 5, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/astroid/nodes/__init__.py", line 26, in <module>
    from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/astroid/nodes/node_classes.py", line 45, in <module>
    from astroid import decorators, mixins, util
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/astroid/decorators.py", line 35, in <module>
    from typing_extensions import ParamSpec
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/typing_extensions.py)
```

### Expected behavior

Should return the pylint report in json file

### Pylint version

```shell
2.11.1
```

### OS / Environment

ubuntu 18.04

### Additional dependencies

pylint-exit 1.2.0
pylint-json2html 0.3.0

**Comment by DanielNoord** [comment]
This was added in https://github.com/PyCQA/astroid/commit/40ea1a3b8e52bbfed43deb1725cde461f4bd8a96

I think we need to put `ParamSpec` after a `if TYPE_CHECKING` statement or add `typing_extensions` to the dependencies (I don't think we want to). However, going to wait on @cdce8p because it is his commit.

**Comment by cdce8p** [comment]
`typing-extensions` is a dependency already for both `pylint` and `astroid`. So the error shouldn't happen.
@vaibhavsdevalalikar Would you mind checking which versions of `typing-extensions` you have installed?
```bash
pip list | grep 'typing-extensions'
```

**Comment by sernot** [comment]
Had the same trace on Arch Linux with pylint 2.11.1. Resolved by removing pip's old typing_extensions and sticking with the newer package provided by system.

**Comment by sylvestre** [comment]
@cdce8p here is what I am getting:
```
$ pip list | grep 'typing-extensions'
typing-extensions   3.10.0.2
```
(I am experiencing the same issue with firefox CI)

**Comment by DanielNoord** [comment]
Could you run `pip show typing-extensions`?

**Comment by sylvestre** [comment]
Sure
```
$ pip show typing-extensions
Name: typing-extensions
Version: 3.10.0.2
Summary: Backported and Experimental Type Hints for Python 3.5+
Home-page: https://github.com/python/typing/blob/master/typing_extensions/README.rst
Author: Guido van Rossum, Jukka Lehtosalo, Łukasz Langa, Michael Lee
Author-email: levkivskyi@gmail.com
License: PSF
Location: /home/sylvestre/dev/mozilla/mozilla-unified/obj-x86_64-pc-linux-gnu/_virtualenvs/common/lib/python3.9/site-packages
Requires: 
Required-by: pylint, astroid, aiohttp
```

**Comment by cdce8p** [comment]
@sylvestre Thanks for bringing this up again. I find it a bit strange to be honest as `3.10.0.2` of `typing-extensions` should work fine (it does for me). Would you mind posting the exact error message?

Additionally, you could check the `typing_extensions.py` file itself to see if it's ok. Based on the output of `pip show` it should be located here
```
/home/sylvestre/dev/mozilla/mozilla-unified/obj-x86_64-pc-linux-gnu/_virtualenvs/common/lib/python3.9/site-packages/typing_extensions.py
```

The file should look similar to this one here: https://github.com/python/typing/blob/3.10.0.2/typing_extensions/src_py3/typing_extensions.py#L2281-L2283
Try to see if you can find `class ParamSpec` somewhere.

**Comment by DanielNoord** [comment]
Would you mind running:
```bash
echo "import typing_extensions
print(typing_extensions)" > test.py
python3 test.py
```

@sernot's reply makes me think that there are two versions of `typing_extensions` on your machine. One installed by `pip` and one pre-installed by the system. Perhaps when you're running python the pre-installed version is being picked up?

**Comment by sylvestre** [comment]
> The file should look similar to this one here: https://github.com/python/typing/blob/3.10.0.2/typing_extensions/src_py3/typing_extensions.py#L2281-L2283 Try to see if you can find `class ParamSpec` somewhere.

Yeah, it is legit. here is what i see:
```
if hasattr(typing, 'ParamSpec'):
    ParamSpec = typing.ParamSpec
else:

    # Inherits from list as a workaround for Callable checks in Python < 3.9.2.
```

@DanielNoord 
```
$ echo "import typing_extensions
print(typing_extensions)" > test.py
$ python3 test.py
<module 'typing_extensions' from '/home/sylvestre/dev/mozilla/mozilla-unified/obj-x86_64-pc-linux-gnu/_virtualenvs/common/lib/python3.9/site-packages/typing_extensions.py'>
```

The log on the firefox side can be seen here to see the full error message (uses Python 3.6)
https://firefoxci.taskcluster-artifacts.net/T33bu3IqR-uSUgjA50LPlA/0/public/logs/live_backing.log

Search for:
```ImportError: cannot import name ```

`/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/bin/pylint", line 8, in <module>     sys.exit(run_pylint())   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/pylint/__init__.py", line 21, in run_pylint     from pylint.lint import Run as PylintRun   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/pylint/lint/__init__.py", line 76, in <module>     from pylint.lint.parallel import check_parallel   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/pylint/lint/parallel.py", line 8, in <module>     from pylint import reporters   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/pylint/reporters/__init__.py", line 26, in <module>     from pylint import utils   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/pylint/utils/__init__.py", line 46, in <module>     from pylint.utils.ast_walker import ASTWalker   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/pylint/utils/ast_walker.py", line 7, in <module>     from astroid import nodes   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/astroid/__init__.py", line 54, in <module>     from astroid import node_classes  # Deprecated, to remove later   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/astroid/node_classes.py", line 5, in <module>     from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/astroid/nodes/__init__.py", line 26, in <module>     from astroid.nodes.node_classes import (  # pylint: disable=redefined-builtin (Ellipsis)   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/astroid/nodes/node_classes.py", line 45, in <module>     from astroid import decorators, mixins, util   File "/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages/astroid/decorators.py", line 35, in <module>     from typing_extensions import ParamSpec ImportError: cannot import name 'ParamSpec'`


(removing the debian package (version 3.7.4.3-1) with ```sudo apt --purge remove python3-typing-extensions ``` did not fix the issue)

**Comment by cdce8p** [comment]
@sylvestre It seems like your `pylint` run is using a different environment
```
/builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages
```
This looks like Python 3.6 instead of Python 3.9 you had for `pip show typing-extensions`.

**Comment by DanielNoord** [comment]
To add to this, the error is actually already reported see:

```
[task 2021-10-04T11:36:59.656Z]  0:39.82 Unable to match yaml regex against output: typing-extensions   3.7.4.3     /builds/worker/checkouts/gecko/obj-x86_64-pc-linux-gnu/_virtualenvs/python-test/lib/python3.6/site-packages pip
...
[task 2021-10-04T11:36:59.656Z]  0:39.82 Unable to match yaml regex against output: pylint 2.11.1 has requirement typing-extensions>=3.10.0; python_version < "3.10", but you have typing-extensions 3.7.4.3.
[task 2021-10-04T11:36:59.656Z]  0:39.82 Unable to match yaml regex against output: astroid 2.8.0 has requirement typing-extensions>=3.10; python_version < "3.10", but you have typing-extensions 3.7.4.3.
```

**Comment by rafikhdj** [comment]
I find a solution that work for me.
- pip uninstall type-extensions
- conda install -c conda-forge typing_extensions
