### ISSUE TITLE
AttributeError: 'FunctionDef' object has no attribute 'type_comment_returns'

### ISSUE THREAD

**Issue by Lucas-C** [PyCQA/pylint#2189]
### Steps to reproduce
1. `https://github.com/PyCQA/pylint`
2. `pip install -e pylint`
3. `pylint pylint`

### Current behavior
```
************* Module pylint
pylint/__init__.py:18:8: E1120: No value for argument 'args' in constructor call (no-value-for-parameter)
Traceback (most recent call last):
  File "/cygdrive/c/Users/admin/.local/share/virtualenvs/pylint/bin/pylint", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/cygdrive/e/code/pylint/bin/pylint", line 3, in <module>
    run_pylint()
  File "/cygdrive/e/code/pylint/pylint/__init__.py", line 18, in run_pylint
    Run(sys.argv[1:])
  File "/cygdrive/e/code/pylint/pylint/lint.py", line 1372, in __init__
    linter.check(args)
  File "/cygdrive/e/code/pylint/pylint/lint.py", line 784, in check
    self._do_check(files_or_modules)
  File "/cygdrive/e/code/pylint/pylint/lint.py", line 917, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/cygdrive/e/code/pylint/pylint/lint.py", line 997, in check_astroid_module
    walker.walk(ast_node)
  File "/cygdrive/e/code/pylint/pylint/utils.py", line 1152, in walk
    self.walk(child)
  File "/cygdrive/e/code/pylint/pylint/utils.py", line 1154, in walk
    cb(astroid)
  File "/cygdrive/e/code/pylint/pylint/checkers/variables.py", line 1500, in leave_functiondef
    super(VariablesChecker3k, self).leave_functiondef(node)
  File "/cygdrive/e/code/pylint/pylint/checkers/variables.py", line 839, in leave_functiondef
    if node.type_comment_returns:
AttributeError: 'FunctionDef' object has no attribute 'type_comment_returns'
```

### Expected behavior
No exception raised

### pylint --version output
```
pylint 2.0.0.dev1
astroid 1.6.5
Python 3.6.1 (default, Mar 21 2017, 21:49:16)
[GCC 5.4.0]
```
I think this bug was introduced in https://github.com/PyCQA/pylint/commit/e62065116

**Comment by PCManticore** [comment]
You need to use the latest astroid installed from the master branch, it doesn't work with  astroid 1.6.5.

**Comment by Lucas-C** [comment]
OK, thanks
