### ISSUE TITLE
`pyreverse` crashes on `main`

### ISSUE THREAD

**Issue by DudeNr33** [PyCQA/pylint#8031]
### Bug description

When running `pyreverse pylint` the program crashes with an `AttributeError`.

### Command used

```shell
pyreverse pylint
```

### Pylint output

```shell
parsing pylint\__init__.py...
[...]
parsing D:\Programming\git-forks\pylint\pylint\utils\__init__.py...
Traceback (most recent call last):
  File "D:\Programming\git-forks\pylint\.venv3104\Scripts\pyreverse-script.py", line 33, in <module>
    sys.exit(load_entry_point('pylint', 'console_scripts', 'pyreverse')())
  File "d:\programming\git-forks\pylint\pylint\__init__.py", line 74, in run_pyreverse
    PyreverseRun(argv or sys.argv[1:])
  File "d:\programming\git-forks\pylint\pylint\pyreverse\main.py", line 228, in __init__
    sys.exit(self.run(args))
  File "d:\programming\git-forks\pylint\pylint\pyreverse\main.py", line 243, in run
    diadefs = handler.get_diadefs(project, linker)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\diadefslib.py", line 225, in get_diadefs
    diagrams.append(generator.class_diagram(project, klass))
  File "d:\programming\git-forks\pylint\pylint\pyreverse\diadefslib.py", line 196, in class_diagram
    self.extract_classes(klass, anc_level, association_level)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\diadefslib.py", line 113, in extract_classes
    self.add_class(klass_node)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\diadefslib.py", line 77, in add_class
    self.linker.visit(node)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\utils.py", line 162, in visit
    methods[0](node)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\inspector.py", line 195, in visit_classdef
    self.associations_handler.handle(assignattr, node)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\inspector.py", line 371, in handle
    if isinstance(node.parent.value, astroid.node_classes.Name):
AttributeError: 'ClassDef' object has no attribute 'value'. Did you mean: 'values'?
```

### Expected behavior

No crash

### Pylint version

```shell
Current main (89a20e2ccdb2927ac370f7c6663fc83318988e10)


pylint 2.16.0-dev
astroid 2.12.14
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
```

Does not occur with v2.15.9.
Introduced with https://github.com/PyCQA/pylint/pull/7836
```


### OS / Environment

pylint 2.16.0-dev
astroid 2.12.14
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]

### Additional dependencies

_No response_

**Comment by DudeNr33** [comment]
Updated the description. If running `pyreverse` over the whole codebase, the crash also appears without the `--class` option.

`pyreverse` succeeds when running over a single file. In this case it only crashes if the `--class` option is supplied as well.
