### ISSUE TITLE
JSON output: AttributeError: 'dict' object has no attribute 'category' since 3.0.0-a4

### ISSUE THREAD

**Issue by angristan** [PyCQA/pylint#4740]
### Steps to reproduce

`fib.py`:

```py
#!/usr/bin/env python
# encoding: utf-8


# Function for nth Fibonacci number
def Fibonacci(n):

    # Check if input is 0 then it will
    # print incorrect input
    if n < 0:
        print("Incorrect input")

    # Check if n is 0
    # then it will return 0
    elif n == 0:
        return 0

    # Check if n is 1,2
    # it will return 1
    elif n == 1 or n == 2:
        return 1

    else:
        return Fibonacci(n-1) + Fibonacci(n-2)

# Driver Program
print(Fibonacci(50))
```

### Current behavior

On `3.0.0-a4`:

```
evenv :: ~ » ./.asdf/installs/python/3.9.5/bin/pylint --version
pylint 3.0.0-a4
astroid 2.6.5
Python 3.9.5 (default, Jun 19 2021, 21:43:39)
[GCC 7.5.0]
devenv :: ~ » ./.asdf/installs/python/3.9.5/bin/pylint fib.py --output-format json
Traceback (most recent call last):
  File "/root/./.asdf/installs/python/3.9.5/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/root/.asdf/installs/python/3.9.5/lib/python3.9/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/root/.asdf/installs/python/3.9.5/lib/python3.9/site-packages/pylint/lint/run.py", line 385, in __init__
    score_value = linter.generate_reports()
  File "/root/.asdf/installs/python/3.9.5/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1256, in generate_reports
    self.reporter.display_messages(report_nodes.Section())
  File "/root/.asdf/installs/python/3.9.5/lib/python3.9/site-packages/pylint/reporters/json_reporter.py", line 31, in display_messages
    json_dumpable = [
  File "/root/.asdf/installs/python/3.9.5/lib/python3.9/site-packages/pylint/reporters/json_reporter.py", line 33, in <listcomp>
    "type": msg.category,
AttributeError: 'dict' object has no attribute 'category'
```

### Expected behavior

Was working on `3.0.0a3`:

```
devenv :: ~ » ./.asdf/installs/python/3.9.5/bin/pylint --version                                                                      24 ↵
pylint 3.0.0a3
astroid 2.6.5
Python 3.9.5 (default, Jun 19 2021, 21:43:39)
[GCC 7.5.0]
devenv :: ~ » ./.asdf/installs/python/3.9.5/bin/pylint fib.py --output-format json
[
    {
        "type": "convention",
        "module": "fib",
        "obj": "",
        "line": 1,
        "column": 0,
        "path": "fib.py",
        "symbol": "missing-module-docstring",
        "message": "Missing module docstring",
        "message-id": "C0114"
    },
    {
        "type": "convention",
        "module": "fib",
        "obj": "Fibonacci",
        "line": 6,
        "column": 0,
        "path": "fib.py",
        "symbol": "invalid-name",
        "message": "Function name \"Fibonacci\" doesn't conform to snake_case naming style",
        "message-id": "C0103"
    },
    {
        "type": "convention",
        "module": "fib",
        "obj": "Fibonacci",
        "line": 6,
        "column": 0,
        "path": "fib.py",
        "symbol": "invalid-name",
        "message": "Argument name \"n\" doesn't conform to snake_case naming style",
        "message-id": "C0103"
    },
    {
        "type": "convention",
        "module": "fib",
        "obj": "Fibonacci",
        "line": 6,
        "column": 0,
        "path": "fib.py",
        "symbol": "missing-function-docstring",
        "message": "Missing function or method docstring",
        "message-id": "C0116"
    },
    {
        "type": "refactor",
        "module": "fib",
        "obj": "Fibonacci",
        "line": 20,
        "column": 9,
        "path": "fib.py",
        "symbol": "consider-using-in",
        "message": "Consider merging these comparisons with \"in\" to 'n in (1, 2)'",
        "message-id": "R1714"
    },
    {
        "type": "refactor",
        "module": "fib",
        "obj": "Fibonacci",
        "line": 6,
        "column": 0,
        "path": "fib.py",
        "symbol": "inconsistent-return-statements",
        "message": "Either all return statements in a function should return an expression, or none of them should.",
        "message-id": "R1710"
    },
    {
        "score": "Your code has been rated at 3.33/10"
    }
]
```

**Comment by Sam152** [comment]
I've checked this out, it looks like this is caused by the score being included in the list of messages that are being dumped:

```
# Message:
{'score': 'Your code has been rated at 5.69/10'}

# Dump code:
        json_dumpable = [
            {
                "type": msg.category,
                ...
            }
            for msg in self.messages
        ]

**Comment by Pierre-Sassoulas** [comment]
Closing as the initial change that caused the problem has been removed from the 3.0 alpha branch.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas What's the current state of the alpha branch? Does it include any relevant changes? And if so, are we tracking those somewhere?

**Comment by Pierre-Sassoulas** [comment]
It's rebased when we release a minor version there's nothing right now. I don't know how we should do this, I don't want to keep rebasing a public branch but I don't want 2.x and 3.x to drift too far away from each other either. Maybe at some point we want to keep the 2.X branch as a maintenance branch and make the 3.0 alpha branch the main branch. But when ? Maybe opening an issue to discuss that would be the thing to do right now.

**Comment by DanielNoord** [comment]
Can't we just yank all alpha's and make we sure we start with `-a5` when we finally do start working on `3.0.0`?

**Comment by Pierre-Sassoulas** [comment]
I can't yank anything on pypi but indicating that it's a pre-release when deploying on github fix the issue we had with dependabot so we don't *need* to rebase. I'm just wondering what happens and how we'll do that when we  start working on 3.0.0.

**Comment by DanielNoord** [comment]
What about not releasing any `3.0.0` anymore and just start from scratch?

Looking at https://pepy.tech/project/pylint we don't really lose that many actual users when we no longer keep it up to date. Those 4k downloads are probably only automated CIs.

**Comment by Pierre-Sassoulas** [comment]
> What about not releasing any 3.0.0 anymore and just start from scratch?

Sure I released nothing from 2.9 to 2.14 and now dependabot do not suggest to upgrade to 3.0 alpha so i don't need to release anything.
