### PR TITLE
Remove type check from arguments-differ

### LINKED ISSUE #4443: Crash when checking function overwrites
### Steps to reproduce

```python
from __future__ import annotations

class Parent:
    async def func(self, user_input: dict[str, int] | None) -> None:
        pass

class Child(Parent):
    async def func(self, user_input: dict[str, int] | None) -> None:
        pass
```

### Current behavior

```
Exception on node <AsyncFunctionDef.func l.10 at 0x104dbf970> in file '/../pylint/a.py'
Traceback (most recent call last):
  File "/../pylint/venv-39_link/bin/pylint", line 33, in <module>
    sys.exit(load_entry_point('pylint', 'console_scripts', 'pylint')())
  File "/../pylint/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/../pylint/pylint/lint/run.py", line 384, in __init__
    linter.check(args)
  File "/../pylint/pylint/lint/pylinter.py", line 919, in check
    self._check_files(
  File "/../pylint/pylint/lint/pylinter.py", line 953, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/../pylint/pylint/lint/pylinter.py", line 979, in _check_file
    check_astroid_module(ast_node)
  File "/../pylint/pylint/lint/pylinter.py", line 1113, in check_astroid_module
    retval = self._check_astroid_module(
  File "/../pylint/pylint/lint/pylinter.py", line 1158, in _check_astroid_module
    walker.walk(ast_node)
  File "/../pylint/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/../pylint/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/../pylint/pylint/utils/ast_walker.py", line 74, in walk
    callback(astroid)
  File "/../pylint/pylint/checkers/classes.py", line 994, in visit_functiondef
    self._check_signature(node, parent_function, "overridden", klass)
  File "/../pylint/pylint/checkers/classes.py", line 1813, in _check_signature
    arg_differ_output = _different_parameters(
  File "/../pylint/pylint/checkers/classes.py", line 354, in _different_parameters
    different_positional = _has_different_parameters(
  File "/../pylint/pylint/checkers/classes.py", line 288, in _has_different_parameters
    if original_type.name != overridden_type.name:
AttributeError: 'BinOp' object has no attribute 'name'
```

### Expected behavior

No error

### pylint --version output

```
pylint 2.8.3.dev15+gce55bce5
astroid 2.5.6
Python 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:05:53) 
[Clang 12.0.5 (clang-1205.0.22.9)]
```

### Additional information
The error is most likely caused by #4422

/CC: @Pierre-Sassoulas @ksaketou

### PR DESCRIPTION
**Pull request by cdce8p**
## Description

Revert part of #4422 to fix crash when checking function overwrites for `arguments-differ`.
`pylint` isn't well suited to check type annotations. That's what type checkers like `mypy` are for which already implement such a check: https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides

/CC: @Pierre-Sassoulas @ksaketou 

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

Closes #4443

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
You're right, we should let mypy do the typing check.
