### ISSUE TITLE
Pyreverse: ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/pylint#22]
Originally reported by: **Jorge Araya Navarro (BitBucket: [shackra](http://bitbucket.org/shackra), GitHub: @shackra?)**

---

I'm not sure what's happening...

```
#!bash

jorge [~/coders/desarrollo/thomas-aquinas] ~> pyreverse -c cocos2d -a 1 -s 1 -f ALL -o png summa/
parsing summa/__init__.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/utils.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/__init__.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/framegrabber.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/summanode.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/collision_model.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/text.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/menu.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/particle.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/batch.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/director.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/shader.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/wired.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/rect.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/skeleton.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/gl_framebuffer_object.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/camera.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/draw.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/tiles.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/custom_clocks.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/path.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/sprite.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/grid.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/particle_systems.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/scene.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/euclid.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/scenes/__init__.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/scenes/transitions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/scenes/pause.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/actions/__init__.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/actions/instant_actions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/actions/base_actions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/actions/grid3d_actions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/actions/camera_actions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/actions/tiledgrid_actions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/actions/move_actions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/actions/basegrid_actions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/actions/interval_actions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/actions/quadmoveby_actions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/__init__.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/music.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/vector.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/system.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/objectbase.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/sftime.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/libs.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/soundstatus.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/actions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/sfmusic.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/effect.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/listener.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/audio/exceptions.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/layer/__init__.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/layer/base_layers.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/layer/util_layers.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/layer/python_interpreter.py...
parsing /home/jorge/coders/desarrollo/thomas-aquinas/summa/layer/scrolling.py...
Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 9, in <module>
    load_entry_point('pylint==0.28.0', 'console_scripts', 'pyreverse')()
  File "/usr/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg/pylint/__init__.py", line 39, in run_pyreverse
    Run(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg/pylint/pyreverse/main.py", line 98, in __init__
    sys.exit(self.run(args))
  File "/usr/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg/pylint/pyreverse/main.py", line 112, in run
    diadefs = handler.get_diadefs(project, linker)
  File "/usr/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg/pylint/pyreverse/diadefslib.py", line 226, in get_diadefs
    diagrams.append(generator.class_diagram(project, klass))
  File "/usr/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg/pylint/pyreverse/diadefslib.py", line 194, in class_diagram
    module, klass = klass.rsplit('.', 1)
ValueError: need more than 1 value to unpack
jorge [~/coders/desarrollo/thomas-aquinas] ~>
```

Then I tried to parse that file directly to see what happen, and I got this:

```
#!bash

jorge [~/coders/desarrollo/thomas-aquinas] ~> pyreverse -c cocos2d -a 1 -s 1 -f ALL -o png summa/layer/scrolling.py
parsing summa/layer/scrolling.py...
Traceback (most recent call last):
  File "/usr/bin/pyreverse", line 9, in <module>
    load_entry_point('pylint==0.28.0', 'console_scripts', 'pyreverse')()
  File "/usr/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg/pylint/__init__.py", line 39, in run_pyreverse
    Run(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg/pylint/pyreverse/main.py", line 98, in __init__
    sys.exit(self.run(args))
  File "/usr/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg/pylint/pyreverse/main.py", line 112, in run
    diadefs = handler.get_diadefs(project, linker)
  File "/usr/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg/pylint/pyreverse/diadefslib.py", line 226, in get_diadefs
    diagrams.append(generator.class_diagram(project, klass))
  File "/usr/lib/python2.7/site-packages/pylint-0.28.0-py2.7.egg/pylint/pyreverse/diadefslib.py", line 199, in class_diagram
    klass = module.ilookup(klass).next()
  File "/usr/lib/python2.7/site-packages/logilab_astng-0.24.3-py2.7.egg/logilab/astng/bases.py", line 124, in _infer_stmts
    raise InferenceError(str(stmt))
logilab.astng.exceptions.InferenceError: None
jorge [~/coders/desarrollo/thomas-aquinas] ~> 
```

The file is right here [shackra/thomas-aquinas/src/summa/layer/scrolling.py](https://bitbucket.org/shackra/thomas-aquinas/src/11d1670d57f848f91cfe794ff0c346b6f8661dfc/summa/layer/scrolling.py?at=stable)...

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/22

**Comment by simsong** [comment]
I had exactly this same problem. It was because I was saying `-c classname` instead of `-c top_level_module.module1.module2.module3.classname`

**Comment by shackra** [comment]
yup, I reported this originally

**Comment by lovasoa** [comment]
I have the same issue. Has there been any progress on this ?

**Comment by Pierre-Sassoulas** [comment]
@lovasoa apparentely no one worked on it yet, I'd be glad to review a merge request that fix this.

**Comment by clavedeluna** [comment]
Is anyone able to provide accessible code (link in original issue isn't) to reproduce this?

**Comment by DudeNr33** [comment]
@clavedeluna theoretically this should work as a minimal example with our own codebase:

```shell
pyreverse -c FileItem pylint
```

As simsong rightly pointed out, the error here is that one needs to provide the fully qualified classname instead, so this should work:
```shell
pyreverse -c pylint.typing.FileItem pylint
```

However another bug is currently hiding it if you try to run this example on our current `main` branch:
```shell
parsing D:\Programming\git-forks\pylint\pylint\utils\utils.py...
    sys.exit(load_entry_point('pylint', 'console_scripts', 'pyreverse')())
  File "d:\programming\git-forks\pylint\pylint\__init__.py", line 74, in run_pyreverse
    PyreverseRun(argv or sys.argv[1:])
  File "d:\programming\git-forks\pylint\pylint\pyreverse\main.py", line 228, in __init__
    sys.exit(self.run(args))
  File "d:\programming\git-forks\pylint\pylint\pyreverse\main.py", line 243, in run
    diadefs = handler.get_diadefs(project, linker)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\diadefslib.py", line 225, in get_diadefs
    diagrams.append(generator.class_diagram(project, klass))
  File "d:\programming\git-forks\pylint\pylint\pyreverse\diadefslib.py", line 196, in class_diagram
    self.extract_classes(klass, anc_level, association_level)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\diadefslib.py", line 113, in extract_classes
    self.add_class(klass_node)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\diadefslib.py", line 77, in add_class
    self.linker.visit(node)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\utils.py", line 162, in visit
    methods[0](node)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\inspector.py", line 195, in visit_classdef
    self.associations_handler.handle(assignattr, node)
  File "d:\programming\git-forks\pylint\pylint\pyreverse\inspector.py", line 371, in handle
    if isinstance(node.parent.value, astroid.node_classes.Name):
AttributeError: 'ClassDef' object has no attribute 'value'. Did you mean: 'values'?
```
It still works on 2.15.9 however. I opened https://github.com/PyCQA/pylint/issues/8031 for the new bug.
