### ISSUE TITLE
pyreverse is broken in pylint==2.0.0.dev0

### ISSUE THREAD

**Issue by jacebrowning** [PyCQA/pylint#2132]
### Steps to reproduce
1. `$ pip install pylint==2.0.0.dev0`
2. `$ pyreverse --help`

### Current behavior

```
Traceback (most recent call last):
  File "/Users/Browning/Documents/zapier/end-to-end/.venv/bin/pyreverse", line 11, in <module>
    sys.exit(run_pyreverse())
  File "/Users/Browning/Documents/zapier/end-to-end/.venv/lib/python3.6/site-packages/pylint/__init__.py", line 30, in run_pyreverse
    Run(sys.argv[1:])
  File "/Users/Browning/Documents/zapier/end-to-end/.venv/lib/python3.6/site-packages/pylint/pyreverse/main.py", line 108, in __init__
    ConfigurationMixIn.__init__(self, usage=__doc__)
  File "/Users/Browning/Documents/zapier/end-to-end/.venv/lib/python3.6/site-packages/pylint/config.py", line 832, in __init__
    OptionsManagerMixIn.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'quiet'
```

### Expected behavior

Help message is shown.

### pylint --version output

```
pylint 2.0.0.dev
astroid 1.6.4
Python 3.6.3 (default, Mar  7 2018, 10:31:42)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

**Comment by jacebrowning** [comment]
I think this broke with https://github.com/PyCQA/pylint/commit/49eae8a9d6e713323cf1a6d6a469ff340255fd6b

**Comment by jacebrowning** [comment]
Thanks for the fix! Could we get a `2.0.0.dev1` release?

**Comment by PCManticore** [comment]
Yup! But not too soon, I'm in vacation this week. Maybe @AWhetter could help if he has some time!

**Comment by AWhetter** [comment]
Both astroid 2.0.0.dev1 and pylint 2.0.0.dev1 have been released.
