### ISSUE TITLE
Recursion depth exceed  RuntimeError on @property poorly named property

### ISSUE THREAD

**Issue by jljuan** [PyCQA/pylint#885]
On a property named 'property', pylint run into a recursion:
```python
class AProperty():
    def __init__(self):
        self._property = None

    @property
    def property(self):
        return self._property

    @property.setter
    def property(self, value):
         self._property = value
 
    @property.deleter
    def property(self):
         del self._property 
```

With :
pylint 1.4.5,
astroid 1.3.8, common 1.2.0
**Python 2.7.11 (default, Feb  4 2016, 09:02:12)**
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]

We get:
`File "/opt/python27/lib/python2.7/site-packages/astroid/bases.py", line 465, in frame
    return self.parent.frame()

RuntimeError: maximum recursion depth exceeded`

With:
pylint 1.4.5,
astroid 1.3.8, common 1.2.0
**Python 3.4.4 (default, Apr 27 2016, 15:36:58)**
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]

We get:
`File "/opt/python34/lib/python3.4/site-packages/astroid/bases.py", line 465, in frame
    return self.parent.frame()

RuntimeError: maximum recursion depth exceeded`

With:
pylint 1.4.5,
astroid 1.3.8, common 1.2.0
**Python 3.5.1 (default, Feb  4 2016, 09:07:25)**
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]

We get:
`Traceback (most recent call last):
  File "/opt/python35/lib/python3.5/site-packages/pylint/lint.py", line 910, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)

  File "/opt/python35/lib/python3.5/site-packages/astroid/manager.py", line 112, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)

  File "/opt/python35/lib/python3.5/site-packages/astroid/builder.py", line 134, in file_build
    module = self._data_build(data, modname, path)

  File "/opt/python35/lib/python3.5/site-packages/astroid/builder.py", line 177, in _data_build
    module = rebuilder.visit_module(node, modname, node_file, package)

  File "/opt/python35/lib/python3.5/site-packages/astroid/rebuilder.py", line 148, in visit_module
    newnode.body = [self.visit(child, newnode) for child in node.body]

  File "/opt/python35/lib/python3.5/site-packages/astroid/rebuilder.py", line 148, in <listcomp>
    newnode.body = [self.visit(child, newnode) for child in node.body]

  File "/opt/python35/lib/python3.5/site-packages/astroid/rebuilder.py", line 161, in visit
    return self._transform(visit_method(node, parent))

  File "/opt/python35/lib/python3.5/site-packages/astroid/rebuilder.py", line 570, in visit_if
    newnode.body = [self.visit(child, newnode) for child in node.body]

  File "/opt/python35/lib/python3.5/site-packages/astroid/rebuilder.py", line 570, in <listcomp>
    newnode.body = [self.visit(child, newnode) for child in node.body]

  File "/opt/python35/lib/python3.5/site-packages/astroid/rebuilder.py", line 161, in visit
    return self._transform(visit_method(node, parent))

  File "/opt/python35/lib/python3.5/site-packages/astroid/rebuilder.py", line 238, in visit_assign
    newnode.value = self.visit(node.value, newnode)

  File "/opt/python35/lib/python3.5/site-packages/astroid/rebuilder.py", line 161, in visit
    return self._transform(visit_method(node, parent))

  File "/opt/python35/lib/python3.5/site-packages/astroid/rebuilder.py", line 331, in visit_callfunc
    if node.starargs is not None:

AttributeError: 'Call' object has no attribute 'starargs'

************* Module mytest
F:  1, 0: <class 'AttributeError'>: 'Call' object has no attribute 'starargs' (astroid-error)`

**Comment by PCManticore** [comment]
This is fixed in https://github.com/PyCQA/astroid/commit/23e59f817bb2fe994e35d64bf06f0234af32053b. But you should definitely change the name of your method, it's poor style to be named after a builtin object and you might cause other issues with pylint later on.

Also in the last traceback, you're getting that error because you're using astroid 1.3.8, which doesn't work on Python 3.5, you need the latest Pylint 1.5.X paired with astroid 1.4.X in order to benefit for this feature.
